services:
  redis:
    image: redis:6-alpine
    container_name: msb_redis
    ports:
      - "6379:6379"
    networks:
      - webservice

  ms_montantmax:
    build: ./src/ms_montantmax
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 50051 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - webservice
    restart: unless-stopped

  ms_profilrisque:
    build: ./src/ms_profilrisque
    ports:
      - "5001:5001"
    depends_on:
      - ms_montantmax
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - webservice
    restart: unless-stopped

  ms_banque:
    build: ./src/ms_banque
    ports:
      - "5002:5002"
    depends_on:
      - redis
      - ms_profilrisque
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 5002 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - webservice
    restart: unless-stopped

  ms_fournisseur:
    build: ./src/ms_fournisseur
    ports:
      - "5003:5003"
    depends_on:
      - ms_banque
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5003/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - webservice
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: src/app/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      ms_montantmax:
        condition: service_healthy
      ms_profilrisque:
        condition: service_healthy
      ms_banque:
        condition: service_healthy
      ms_fournisseur:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - webservice
    restart: unless-stopped

networks:
  webservice:
    driver: bridge
