# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import montantmax_pb2 as montantmax__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in montantmax_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MontantMaxServiceStub(object):
    """Définition du service gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckLoan = channel.unary_unary(
                '/ms_montantmax.MontantMaxService/CheckLoan',
                request_serializer=montantmax__pb2.LoanRequest.SerializeToString,
                response_deserializer=montantmax__pb2.LoanResponse.FromString,
                _registered_method=True)


class MontantMaxServiceServicer(object):
    """Définition du service gRPC
    """

    def CheckLoan(self, request, context):
        """Méthode pour vérifier le montant du prêt
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MontantMaxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckLoan,
                    request_deserializer=montantmax__pb2.LoanRequest.FromString,
                    response_serializer=montantmax__pb2.LoanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ms_montantmax.MontantMaxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ms_montantmax.MontantMaxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MontantMaxService(object):
    """Définition du service gRPC
    """

    @staticmethod
    def CheckLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ms_montantmax.MontantMaxService/CheckLoan',
            montantmax__pb2.LoanRequest.SerializeToString,
            montantmax__pb2.LoanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
